Allow `eshell-toggle-init-eshell` to search Git root.
4DA/eshell-toggle pull request #12
Opened 2020-09-26 18:57 UTC by masamu

This commit allows `eshell-toggle-init-eshell` to first look for Git
root directory first, if not found falls back to default DIR.

In principle this can be refactored out as a function that returns
DIR (default-directory or/and look for Git root directory if user choose so) and let `
eshell-toggle-init-eshell`, `eshell-toggle-init-ansi-term` and
`eshell-toggle-init-tmux` fetch from it.

2020-09-26 19:47 UTC, 4DA commented
This will be a great feature.

Please `defcustom` similar to `eshell-toggle-use-projectile-root` to toggle this feature. I'd like to keep this feature disabled by default to preserve current behaviour for users.

Also, could you please extend `eshell-toggle--get-directory()` function so that it returns git-root-directory if `eshell-toggle-use-projectile-root` is not set and new `eshell-toggle-use-git-root` is set.

Thank you.

2020-09-26 22:44 UTC, masamu commented
This last commit makes the modifications necessary to ` eshell-toggle--get-directory ` and creates a defcustom for the user.

Please tell me if everything is alright, I can squash the commits if want to.

One special case is when both projectile and git options are turned on. In this case projectile should come first in priority, I think this is OK, what do you think?

2020-09-27 10:24 UTC, 4DA requested changes
We are almost there. Yes, projectile should come first. Please fix comment, squash and we are ready to merge. @a13 do you have any suggestions?

2020-09-27 10:24 UTC, 4DA commented on eshell-toggle.el
> +  "Init `eshell' buffer with DIR. Try to find root of Git first, otherwise fallback to DIR."
Please revert this comment.

2020-09-27 16:57 UTC, merged