Support in-built Project.el
4DA/eshell-toggle pull request #18
Opened 2023-08-04 15:04 UTC by CsBigDataHub

@4DA please review.

2023-08-08 13:30 UTC, CsBigDataHub commented
@4DA friendly ping.

2023-08-10 00:22 UTC, a13 commented on eshell-toggle.el
> +  (or
better use `cond`, since the `else` parts of both `if` branches look the same

2023-08-10 00:24 UTC, a13 commented on eshell-toggle.el
> +(defcustom eshell-toggle-use-project-root
probably we should just add another option to `eshell-toggle-use-projectile-root`, smth like `nil` for "Disabled", `t` and `'projectile` for projectile, and `'project` for using project.el. And

2023-09-24 18:21 UTC, 4DA requested changes
please follow @a13 advice: make add eshell-toggle-use-projectile-root accept different values: nil, ‘projectile, ‘project

also please refactor to cond clause on line 150 as advised

2024-03-17 23:13 UTC, brsvh commented
@CsBigDataHub are you still continuing this work? I followed the review and created a revision, maybe you can pick my work, [patch here].

[patch here]: https://github.com/brsvh/eshell-toggle/compare/100e7069b428b2cf65b1d3cd987234e0b9d4deb3..6611888be2fe834f044db26436ac3f977858f5c8

2024-03-25 16:00 UTC, CsBigDataHub commented
Updated.

Thank you @brsvh, @a13 , @4DA .

2024-04-15 13:36 UTC, ChetanKoneru commented
> Updated.
> 
> Thank you @brsvh, @a13 , @4DA .

@4DA  friendly ping. Thank you.

2024-04-17 15:36 UTC, merged

2024-04-17 15:36 UTC, 4DA commented
@CsBigDataHub merged, thank you for contribution!